### ISSUE TITLE
Fatal error after installation

### ISSUE THREAD

**Issue by mariamghalleb** [sashas777/bug-from-email#2]
Hello , 
I'm on magento 2.2.4, php 7.
I got this right after enabling the module, please see attached. 

![capturesa](https://user-images.githubusercontent.com/28814080/42183858-48634cc8-7e3b-11e8-8e2b-54fe9931ee4f.PNG)

**Comment by sashas777** [comment]
@mariamghalleb 

Can you please show what is your deploy mode? 
```
bin/magento deploy:mode:show
```

Did you do composer installation or what steps to follow in order to repeat it?

**Comment by mariamghalleb** [comment]
i'm on a developer mode, and i didn't composer install, i copied the "module" manually

**Comment by sashas777** [comment]
@mariamghalleb 

Can you try to install it using composer, please?
It will get the latest version of the module
```
composer require sashas/bug-from-email
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
```

**Comment by mariamghalleb** [comment]
I'm sorry I can't, I manually edited  SenderBuilder.php and fixed the issue, thank you for your help though!

**Comment by sashas777** [comment]
@mariamghalleb 

Can you share what did you edit? Maybe it would help others?

Thanks

**Comment by mariamghalleb** [comment]
A simple fix instead of installing a module is to do like below until fixed in next release:

Goto **>. ..../vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php**
Edit **the configureEmailTemplate() function** and add this line `$this->transportBuilder->setFrom($this->identityContainer->getEmailIdentity());`

**The function has to be as follows:** 

```
protected function configureEmailTemplate()
{
$this->transportBuilder->setTemplateIdentifier($this->templateContainer->getTemplateId());
$this->transportBuilder->setTemplateOptions($this->templateContainer->getTemplateOptions());
$this->transportBuilder->setTemplateVars($this->templateContainer->getTemplateVars());
$this->transportBuilder->setFrom($this->identityContainer->getEmailIdentity());
//the below are commented
//$this->transportBuilderByStore->setFromByStore(  
//    $this->identityContainer->getEmailIdentity(), 
//    $this->identityContainer->getStore()->getId() 
// );
}
```

Credit to https://github.com/msawyers.

**Comment by sashas777** [comment]
@mariamghalleb 

Thanks

**Comment by mariamghalleb** [comment]
thanks to you too !
