### ISSUE TITLE
Will it work on 2.2.6?

### ISSUE THREAD

**Issue by iget-master** [sashas777/bug-from-email#8]
Since the problem wasn't fixed on 2.2.6, can this package fix it?

**Comment by sashas777** [comment]
@iget-master 
The package has been updated. I havent test it on 2.2.6 but others say it fixes it

**Comment by iget-master** [comment]
Hi, I've tested, and look like it doesn't fix. :( Do you have any tips to help me to track the issue cause?

**Comment by sashas777** [comment]
@iget-master  I would better see the original issue: https://github.com/magento/magento2/issues/14952 There may be some advice.
