### ISSUE TITLE
2.2.7

### ISSUE THREAD

**Issue by ymarc77** [sashas777/bug-from-email#9]

**Comment by ymarc77** [comment]
Any update for 2.2.7?

**Comment by jossenisse** [comment]
I am also wondering if any update for 2.2.7?

**Comment by sashas777** [comment]
@ymarc77  @jossenisse  

Is it still happens at the 2.2.7? I can update release but not able to test.

**Comment by ymarc77** [comment]
@sashas777 It seems to work perfecto on 2.2.7

**Comment by sashas777** [comment]
Updated composer for 2.2.7
